### ISSUE TITLE
Would it be better just to have 4 meta arguments for each corner?

### ISSUE THREAD

**Issue by andyofsmeg** [andyofsmeg/ggTag#7]
Then just make all the date, path stuff options.  A separate function could then be created where the current set-up is the default (i.e. path in bottom left, date in bottom right etc

**Comment by andyofsmeg** [comment]
Thinking the current defaults could be in a function called pharmaTag, main ggTag would then have arguments of title, metaTopLeft, metaTopRight, metaBottomLeft, metaBottomRight

**Comment by aimeegott** [comment]
What will be the best way to control position? Currently they are all fixed based on locations that are expected but if you wanted to put for example the date in the bottom left instead of right the position arguments need to change. Is that controllable based on where it is being placed?

**Comment by aimeegott** [comment]
Created a new branch to test this development on

**Comment by andyofsmeg** [comment]
Resolving as the single meta argument with positions and splitting into a generci and specific pharmaTag function effectively fixed this.
